theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
mouse = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending"]

[editor.indent-guides]
render = true
character = "."

[keys.normal]
C-g = ":run-shell-command ~/.config/helix/scripts/yazi-chooser.sh"
